### ISSUE TITLE
Obtaining cage mesh from optimized grid 

### ISSUE THREAD

**Issue by sookim813** [xth430/deforming-nerf#2]
Hello. Thank you for your wonderful work. 

I have a question about training the custom dataset.
I have images, mesh from those images, and deformed mesh, and I want to render them with your deforming-nerf code.
The problem is my meshes are not cage-mesh. How can I transform regular mesh into cage mesh?

Could you please give some instructions regarding the custom dataset training part including how to build cage-mesh?

Thank you

**Comment by xth430** [comment]
Hi, thanks for your comment.
We will add code and instructions for obtaining mesh and cage.

**Comment by xth430** [comment]
Hi, please check the manual [here](https://github.com/xth430/deforming-nerf/blob/main/MANUAL.md).
