### ISSUE TITLE
Move vertices,mesh became not wartertight

### ISSUE THREAD

**Issue by Seagullflysxt** [xth430/deforming-nerf#4]
Hi, I moved some verteces of your provided deformed chair cage ,and also keep the vertex order when export.
And then I ran:
```shell
python render_imgs_deform.py ckpt/nerf_lego/ckpt.npz ../data/nerf_synthetic/lego/ -c configs/syn.json --interpolate --cam_id 64
```
I got 
```shell
Traceback (most recent call last):
  File "render_imgs_deform.py", line 93, in <module>
    cage_source, cage_target = load_cages(args)
  File "/root/deforming-nerf/opt/deformation/util.py", line 19, in load_cages
    assert cage_target.is_watertight, "Cage (target) is not watertight!"
AssertionError: Cage (target) is not watertight!
```

It seems the cage  I deformed became not wartertight anymore,but I look it up in blender, it seems nowhere is unclosed.
Could you give me some advices help to move the vertices while keep the mesh wartertight?

**Comment by xth430** [comment]
Hi, could you share the deformed cage with me so that I can take a look? A common issue is self-intersection which can cause the cage to be non-watertight.

**Comment by Seagullflysxt** [comment]
Sure,thanks for your help:)
[non_watertight.zip](https://github.com/xth430/deforming-nerf/files/10893585/non_watertight.zip)

I think I found where went wrong....blender clicked something unnecessory when export the mesh....
Thanks for your work:)
